In [2]:
import numpy as np

a = np.arange(10) ## like embeded function in python # chainer numpy intro = array(range(10))

print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
a2 = np.arange(10).reshape([2,5])
print(a2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
import random
## def exercise
def randomf(x1, x2):
    y = random.randint(0,10)*x1*x2
    return y 


n1 = 10
n2 = 3
print("func test: ", randomf(n1, n2))


func test:  180
y


In [11]:
## char test
str = "my name is ryota"
print(str[1])  #y

#str = "your name is Wan mingwue whose chinese girl I like"
print(str)

my name is ryota


In [23]:
# input
io1 = input(">>")

print(io1)

# arg
import sys
args = sys.argv

## from jupyter, unknow responce
print(args[1])
print(args[2])


>>3
3
-f
C:\Users\jaistRT\AppData\Roaming\jupyter\runtime\kernel-056b3733-9042-431a-ac46-fbe82d366447.json


In [26]:
#format print 
print ("サイト開設 %d 日目！ %s" %(111, "abc"))


サイト開設 111 日目！ abc


In [32]:
# list experss

#list multi operate


list1 = [3+a+b for a,b in zip(range(5,10), range(4,9))]
print(list1)

[12, 14, 16, 18, 20]


In [29]:
#(diary)